"""TixTime HTTP API.

Two contracts run through every endpoint here:

AS-OF. Nothing means "now". Every price-bearing endpoint takes an `as_of`
query parameter defaulting to the configured clock, and never reads a snapshot
dated after it. The warehouse physically contains the whole future path (the
simulator generated it), so this is the boundary that stops the site from
reading answers out of the back of the book.

PROVENANCE. Every response carrying a price carries `source` and
`is_simulated` alongside it. A column in the database is invisible at the
surface where harm happens and is dropped by the first aggregation; the flag
travels with the number instead.
"""

from __future__ import annotations

import json
from datetime import date, timedelta
from typing import Any

from fastapi import Depends, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from tixtime import db
from tixtime.alerts import engine as alerts
from tixtime.config import REPORT_DIR, SYNTHETIC_SOURCE, as_of_date
from tixtime.ml import serve

DISCLAIMER = (
    "Prices are simulated. The SeatGeek export this catalogue is built from has every "
    "price column redacted, and no ticket API is reachable from this deployment, so the "
    "price history and every figure derived from it are generated by TixTime's market "
    "simulator. Event names, dates, venues and purchase links are real."
)

app = FastAPI(
    title="TixTime API",
    version="1.0.0",
    description="Ticket buy-timing predictions over a real event catalogue with simulated prices.",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def get_connection():
    con = db.connect(read_only=False)
    try:
        yield con
    finally:
        con.close()


def resolve_as_of(as_of: date | None = Query(default=None)) -> date:
    return as_of or as_of_date()


def _records(frame) -> list[dict]:
    """DataFrame -> JSON-safe records.

    DuckDB returns NaN for SQL NULL in numeric columns and numpy scalars
    everywhere; json.dumps rejects both ("Out of range float values are not
    JSON compliant"). Every DataFrame leaving this module goes through here.
    """
    import numpy as np
    import pandas as pd

    if frame is None or len(frame) == 0:
        return []
    cleaned = frame.replace({np.nan: None, np.inf: None, -np.inf: None})
    records = cleaned.to_dict("records")
    out = []
    for record in records:
        row = {}
        for key, value in record.items():
            if value is None or (isinstance(value, float) and value != value):
                row[key] = None
            elif isinstance(value, (np.integer,)):
                row[key] = int(value)
            elif isinstance(value, (np.floating,)):
                row[key] = None if np.isnan(value) else float(value)
            elif isinstance(value, (np.bool_,)):
                row[key] = bool(value)
            elif isinstance(value, pd.Timestamp):
                # DuckDB DATE columns arrive as midnight Timestamps. Emitting
                # them with a time component makes the same logical date
                # compare unequal to a plain "YYYY-MM-DD" from another
                # endpoint, so dates stay date-shaped.
                row[key] = (
                    value.date().isoformat()
                    if (value.hour, value.minute, value.second, value.microsecond) == (0, 0, 0, 0)
                    else value.isoformat()
                )
            elif isinstance(value, date):
                row[key] = value.isoformat()
            else:
                row[key] = value
        out.append(row)
    return out


def _iso(value) -> str | None:
    """Dates may already be isoformat strings by the time they reach here,
    because _records normalises them. Accept either."""
    if value is None:
        return None
    return value.isoformat() if hasattr(value, "isoformat") else str(value)


def board_as_of(con) -> date | None:
    """The single as-of date the precomputed deal board was built for."""
    row = con.execute("SELECT max(as_of_date) FROM deal_board").fetchone()
    return row[0] if row and row[0] else None


def _provenance(as_of: date, con=None) -> dict[str, Any]:
    payload = {
        "as_of": as_of.isoformat(),
        "source": SYNTHETIC_SOURCE,
        "is_simulated": True,
        "disclaimer": DISCLAIMER,
    }
    if con is not None:
        # The deal board and sparklines are precomputed for ONE date. Serving
        # them for a different as_of would hand back predictions derived from
        # prices after the date the response claims -- and the clock control
        # actively invites moving the clock. So the board is filtered to its
        # own date, and the response says plainly when it does not cover the
        # requested one.
        built = board_as_of(con)
        payload["board_as_of"] = built.isoformat() if built else None
        payload["board_covers_as_of"] = built == as_of
        if built != as_of:
            payload["board_note"] = (
                f"The ranked deal board was built for {built}. Rankings, sparklines and "
                f"buy signals are unavailable for {as_of}; per-event forecasts on the event "
                f"page are still computed live and remain correct. Rebuild with "
                f"`python -m tixtime.ml.precompute --as-of {as_of}`."
            )
    return payload


# ---------------------------------------------------------------------------
# Meta
# ---------------------------------------------------------------------------


@app.get("/api/meta")
def meta(con=Depends(get_connection), as_of: date = Depends(resolve_as_of)):
    counts = con.execute(
        """
        SELECT
          (SELECT count(*) FROM events)                                AS events,
          (SELECT count(*) FROM events WHERE is_modelable)             AS modelable,
          (SELECT count(*) FROM events WHERE event_date > ? AND is_modelable) AS upcoming,
          (SELECT count(*) FROM venues)                                AS venues,
          (SELECT count(*) FROM franchises WHERE event_count > 0)      AS teams,
          (SELECT count(*) FROM price_snapshots)                       AS snapshots
        """,
        [as_of],
    ).fetchone()
    # Restricted to modelable events on purpose: the export carries nine rows
    # with corrupt dates out in 2056, and letting them define the catalogue
    # window would push the clock control's range 30 years past the data.
    window = con.execute(
        "SELECT min(event_date), max(event_date) FROM events WHERE is_modelable"
    ).fetchone()
    model_version = con.execute(
        "SELECT detail FROM pipeline_runs WHERE stage='train' ORDER BY ran_at DESC LIMIT 1"
    ).fetchone()
    return {
        **_provenance(as_of, con),
        "catalogue": {
            "events": counts[0],
            "modelable_events": counts[1],
            "upcoming_events": counts[2],
            "venues": counts[3],
            "teams": counts[4],
            "price_snapshots": counts[5],
            "catalogue_start": window[0].isoformat() if window[0] else None,
            "catalogue_end": window[1].isoformat() if window[1] else None,
        },
        "model_version": model_version[0] if model_version else None,
        "clock_note": (
            "The catalogue runs to "
            f"{window[1].isoformat() if window[1] else 'mid-2026'}, which real-world today has "
            "passed. TixTime therefore runs on an explicit as-of date: events before it are "
            "history used for training and backtesting, events after it are what the site "
            "recommends on. Move the clock to replay any date."
        ),
    }


@app.get("/api/filters")
def filters(con=Depends(get_connection), as_of: date = Depends(resolve_as_of)):
    """Facet values with counts, so the filter rail is populated not empty."""

    def facet(sql: str) -> list[dict]:
        return [
            {"value": row[0], "label": row[1], "count": row[2]}
            for row in con.execute(sql, [as_of]).fetchall()
            if row[0] is not None
        ]

    return {
        **_provenance(as_of, con),
        "leagues": facet(
            "SELECT league, upper(league), count(*) FROM events "
            "WHERE event_date > ? AND league IS NOT NULL GROUP BY 1,2 ORDER BY 3 DESC"
        ),
        "cities": facet(
            "SELECT v.city, v.city || ', ' || v.region, count(*) FROM events e "
            "JOIN venues v USING (venue_id) WHERE e.event_date > ? AND v.city IS NOT NULL "
            "GROUP BY 1,2 ORDER BY 3 DESC LIMIT 60"
        ),
        "venues": facet(
            "SELECT CAST(v.venue_id AS VARCHAR), v.venue_name, count(*) FROM events e "
            "JOIN venues v USING (venue_id) WHERE e.event_date > ? GROUP BY 1,2 ORDER BY 3 DESC LIMIT 80"
        ),
        "teams": facet(
            "SELECT e.home_slug, e.home_team, count(*) FROM events e "
            "WHERE e.event_date > ? AND e.home_team IS NOT NULL GROUP BY 1,2 ORDER BY 3 DESC LIMIT 120"
        ),
        "postseason_tiers": facet(
            "SELECT postseason_tier, replace(postseason_tier,'_',' '), count(*) FROM events "
            "WHERE event_date > ? GROUP BY 1,2 ORDER BY 3 DESC"
        ),
    }


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------

_SEARCH_SQL = """
SELECT e.event_id, e.name, e.short_name, e.league, e.event_date, e.event_datetime_utc,
       e.home_team, e.away_team, e.postseason_tier, e.is_ga, e.seat_selection,
       e.is_tbd, e.is_modelable, e.exclusion_reason, e.url,
       v.venue_name, v.city, v.region, v.archetype,
       d.tier_key, d.price_now, d.forecast_min, d.forecast_min_date,
       d.days_to_forecast_min, d.expected_saving, d.expected_saving_pct,
       d.action, d.confidence, d.days_until_event,
       s.points AS sparkline
FROM events e
JOIN venues v USING (venue_id)
LEFT JOIN (
    SELECT * FROM deal_board
    WHERE as_of_date = ?
    QUALIFY row_number() OVER (PARTITION BY event_id ORDER BY expected_saving_pct DESC) = 1
) d ON d.event_id = e.event_id
LEFT JOIN event_sparkline s ON s.event_id = e.event_id AND s.tier_key = d.tier_key
WHERE e.event_date > ?
"""


def _event_row(row: dict, as_of: date, board_current: bool = True) -> dict:
    forecastable, reason = _forecastability(row, board_current)
    return {
        "event_id": row["event_id"],
        "name": row["name"],
        "short_name": row["short_name"],
        "league": row["league"],
        "event_date": _iso(row["event_date"]),
        "home_team": row["home_team"],
        "away_team": row["away_team"],
        "postseason_tier": row["postseason_tier"],
        "venue_name": row["venue_name"],
        "city": row["city"],
        "region": row["region"],
        "is_ga": bool(row["is_ga"]),
        "seat_selection": bool(row["seat_selection"]),
        "is_forecastable": forecastable,
        "unforecastable_reason": reason,
        "purchase_url": row["url"],
        "days_until_event": row.get("days_until_event"),
        "best_tier": row.get("tier_key"),
        "price_now": row.get("price_now"),
        "forecast_min": row.get("forecast_min"),
        "forecast_min_date": _iso(row.get("forecast_min_date")),
        "days_to_forecast_min": row.get("days_to_forecast_min"),
        "expected_saving": row.get("expected_saving"),
        "expected_saving_pct": row.get("expected_saving_pct"),
        "action": row.get("action"),
        "confidence": row.get("confidence"),
        "sparkline": json.loads(row["sparkline"]) if row.get("sparkline") else None,
        "source": SYNTHETIC_SOURCE,
        "is_simulated": True,
    }


def _forecastability(row: dict, board_current: bool = True) -> tuple[bool, str | None]:
    """Why an event has no forecast, stated rather than rendered as a blank chart."""
    if row.get("is_tbd"):
        return False, "date_tbd"
    if not row.get("is_modelable"):
        return False, row.get("exclusion_reason") or "not_modelable"
    if row.get("price_now") is None:
        # Distinguish "this event genuinely has no price history" from "the
        # ranked board simply was not built for this clock date". Conflating
        # them told the user no observations existed while the chart below
        # drew a hundred of them.
        return False, "no_snapshots" if board_current else "board_not_built"
    return True, None


@app.get("/api/search")
def search(
    con=Depends(get_connection),
    as_of: date = Depends(resolve_as_of),
    q: str | None = None,
    league: str | None = None,
    city: str | None = None,
    venue_id: int | None = None,
    team: str | None = None,
    postseason_tier: str | None = None,
    date_from: date | None = None,
    date_to: date | None = None,
    max_price: float | None = None,
    action: str | None = None,
    # Default to events that can actually be forecast. The catalogue contains
    # 1,316 stadium tours and other non-game inventory which sort to the front
    # by date and would otherwise fill the entire first page with rows reading
    # "No forecast" -- the product's worst possible first impression.
    include_unforecastable: bool = False,
    sort: str = Query("date", pattern="^(date|saving|price|name)$"),
    limit: int = Query(60, le=200),
    offset: int = 0,
):
    # First param feeds the deal_board subquery, second the event_date filter.
    clauses, params = [], [as_of, as_of]
    # When the board does not cover this date there are no predictions to
    # filter on, so fall back to the catalogue rather than returning nothing:
    # the events are still browsable and their per-event forecasts are still
    # computed live and correct.
    board_current = board_as_of(con) == as_of
    if not include_unforecastable and board_current:
        clauses.append("e.is_modelable AND d.price_now IS NOT NULL")
    elif not include_unforecastable:
        clauses.append("e.is_modelable")
    if q:
        clauses.append(
            "(lower(e.name) LIKE ? OR lower(v.venue_name) LIKE ? OR lower(v.city) LIKE ?)"
        )
        params += [f"%{q.lower()}%"] * 3
    if league:
        clauses.append("e.league = ?"); params.append(league)
    if city:
        clauses.append("v.city = ?"); params.append(city)
    if venue_id:
        clauses.append("e.venue_id = ?"); params.append(venue_id)
    if team:
        clauses.append("(e.home_slug = ? OR lower(e.away_team) = ?)")
        params += [team, team.replace("-", " ").lower()]
    if postseason_tier:
        clauses.append("e.postseason_tier = ?"); params.append(postseason_tier)
    if date_from:
        clauses.append("e.event_date >= ?"); params.append(date_from)
    if date_to:
        clauses.append("e.event_date <= ?"); params.append(date_to)
    if max_price is not None:
        clauses.append("d.price_now <= ?"); params.append(max_price)
    if action:
        clauses.append("d.action = ?"); params.append(action)

    where = (" AND " + " AND ".join(clauses)) if clauses else ""
    order = {
        "date": "e.event_date ASC, e.event_id ASC",
        "saving": "d.expected_saving_pct DESC NULLS LAST, e.event_date ASC",
        "price": "d.price_now ASC NULLS LAST",
        "name": "e.name ASC",
    }[sort]

    total = con.execute(
        f"SELECT count(*) FROM ({_SEARCH_SQL}{where}) t", params
    ).fetchone()[0]
    rows = _records(con.execute(
        f"{_SEARCH_SQL}{where} ORDER BY {order} LIMIT {int(limit)} OFFSET {int(offset)}", params
    ).df())

    return {
        **_provenance(as_of, con),
        "total": total,
        "limit": limit,
        "offset": offset,
        "results": [_event_row(row, as_of, board_current) for row in rows],
    }


@app.get("/api/deals")
def deals(
    con=Depends(get_connection),
    as_of: date = Depends(resolve_as_of),
    league: str | None = None,
    city: str | None = None,
    venue_id: int | None = None,
    team: str | None = None,
    tier_key: str | None = None,
    date_from: date | None = None,
    date_to: date | None = None,
    max_price: float | None = None,
    min_saving_pct: float = 0.0,
    limit: int = Query(80, le=300),
    offset: int = 0,
):
    """Cross-event ranked board: where is waiting worth the most, right now?

    This is the question the product exists to answer, and it is a comparison
    across events, not a per-event lookup -- so it is served from the
    precomputed deal_board rather than by fanning out model calls.
    """
    clauses = ["e.event_date > ?", "d.expected_saving_pct >= ?", "d.as_of_date = ?"]
    params: list = [as_of, min_saving_pct, as_of]
    if league:
        clauses.append("e.league = ?"); params.append(league)
    if city:
        clauses.append("v.city = ?"); params.append(city)
    if venue_id:
        clauses.append("e.venue_id = ?"); params.append(venue_id)
    if team:
        clauses.append("e.home_slug = ?"); params.append(team)
    if tier_key:
        clauses.append("d.tier_key = ?"); params.append(tier_key)
    if date_from:
        clauses.append("e.event_date >= ?"); params.append(date_from)
    if date_to:
        clauses.append("e.event_date <= ?"); params.append(date_to)
    if max_price is not None:
        clauses.append("d.price_now <= ?"); params.append(max_price)

    where = " AND ".join(clauses)
    sql = f"""
        SELECT e.event_id, e.name, e.league, e.event_date, e.home_team, e.away_team,
               e.postseason_tier, e.is_ga, e.url, v.venue_name, v.city, v.region,
               d.tier_key, t.label AS tier_label, d.price_now, d.forecast_min,
               d.forecast_min_date, d.days_to_forecast_min, d.expected_saving,
               d.expected_saving_pct, d.action, d.confidence, d.days_until_event
        FROM deal_board d
        JOIN events e USING (event_id)
        JOIN venues v USING (venue_id)
        LEFT JOIN seat_tiers t ON t.tier_key = d.tier_key AND t.archetype = v.archetype
        WHERE {where}
    """
    total = con.execute(f"SELECT count(*) FROM ({sql}) x", params).fetchone()[0]
    rows = con.execute(
        f"{sql} ORDER BY d.expected_saving_pct DESC, d.expected_saving DESC "
        f"LIMIT {int(limit)} OFFSET {int(offset)}",
        params,
    ).df()

    records = []
    for row in _records(rows):
        records.append(
            {
                **{
                    k: (v.isoformat() if isinstance(v, date) else v)
                    for k, v in row.items()
                },
                "tier_label": row.get("tier_label") or row["tier_key"],
                "source": SYNTHETIC_SOURCE,
                "is_simulated": True,
            }
        )
    return {**_provenance(as_of, con), "total": total, "limit": limit, "offset": offset, "deals": records}


# ---------------------------------------------------------------------------
# Event detail
# ---------------------------------------------------------------------------


@app.get("/api/events/{event_id}")
def event_detail(event_id: int, con=Depends(get_connection), as_of: date = Depends(resolve_as_of)):
    rows = con.execute(
        """
        SELECT e.*, v.venue_name, v.city, v.region, v.archetype, v.capacity
        FROM events e JOIN venues v USING (venue_id) WHERE e.event_id = ?
        """,
        [event_id],
    ).df()
    if rows.empty:
        raise HTTPException(404, f"event {event_id} not found")
    row = rows.to_dict("records")[0]

    board = con.execute(
        """
        SELECT d.*, t.label AS tier_label, t.tier_rank
        FROM deal_board d
        LEFT JOIN seat_tiers t ON t.tier_key = d.tier_key
             AND t.archetype = (SELECT archetype FROM venues WHERE venue_id = ?)
        WHERE d.event_id = ? AND d.as_of_date = ? ORDER BY t.tier_rank NULLS LAST
        """,
        [row["venue_id"], event_id, as_of],
    ).df()
    board = _records(board)

    forecastable, reason = _forecastability(
        {**row, "price_now": board[0]["price_now"] if board else None},
        board_current=board_as_of(con) == as_of,
    )
    # row comes straight from a DataFrame here, so event_date is a Timestamp;
    # comparing it to a date raises rather than coercing.
    event_day = row["event_date"]
    if event_day is not None and hasattr(event_day, "date"):
        event_day = event_day.date()
    if event_day and event_day <= as_of:
        forecastable, reason = False, "past_event"

    return {
        **_provenance(as_of, con),
        "event": {
            "event_id": row["event_id"],
            "name": row["name"],
            "league": row["league"],
            "event_type": row["event_type"],
            "event_date": _iso(row["event_date"]),
            "event_datetime_utc": (
                row["event_datetime_utc"].isoformat() if row["event_datetime_utc"] else None
            ),
            "home_team": row["home_team"],
            "away_team": row["away_team"],
            "postseason_tier": row["postseason_tier"],
            "venue_name": row["venue_name"],
            "city": row["city"],
            "region": row["region"],
            "capacity": row["capacity"],
            "is_ga": bool(row["is_ga"]),
            # These two real columns decide whether a seat switcher is even
            # meaningful. A GA event has no sections; showing a tier picker for
            # one is a factual error a user catches in a single click.
            "seat_selection": bool(row["seat_selection"]),
            "has_seat_tiers": bool(row["seat_selection"]) and not bool(row["is_ga"]),
            "is_forecastable": forecastable,
            "unforecastable_reason": reason,
            "purchase_url": row["url"],
            "announce_date": _iso(row["announce_date"]),
        },
        "tiers": [
            {
                **{k: (v.isoformat() if isinstance(v, date) else v) for k, v in tier.items()},
                "tier_label": tier.get("tier_label") or tier["tier_key"],
            }
            for tier in board
        ],
    }


@app.get("/api/events/{event_id}/timeline")
def timeline(
    event_id: int,
    tier_key: str | None = None,
    con=Depends(get_connection),
    as_of: date = Depends(resolve_as_of),
):
    """History + forecast + recommendation in ONE call.

    The hero chart needs all three on a single date axis. Splitting them across
    endpoints invites the client to stitch series that were computed against
    different as-of dates, which would silently misalign the chart.
    """
    event = con.execute(
        "SELECT e.*, v.archetype FROM events e JOIN venues v USING (venue_id) WHERE e.event_id = ?",
        [event_id],
    ).df()
    if event.empty:
        raise HTTPException(404, f"event {event_id} not found")
    event_row = event.to_dict("records")[0]

    if tier_key is None:
        picked = con.execute(
            "SELECT tier_key FROM deal_board WHERE event_id = ? AND as_of_date = ? "
            "ORDER BY expected_saving_pct DESC LIMIT 1",
            [event_id, as_of],
        ).fetchone()
        # The board only covers one date. Falling back to the snapshots keeps
        # the price chart rendering at any clock date -- history and forecast
        # are computed live and stay correct even when the ranked board does
        # not cover the date.
        if picked is None:
            picked = con.execute(
                "SELECT tier_key FROM price_snapshots WHERE event_id = ? AND NOT is_burn_in "
                "GROUP BY tier_key ORDER BY min(get_in_price) LIMIT 1",
                [event_id],
            ).fetchone()
        tier_key = picked[0] if picked else None
    if tier_key is None:
        return {**_provenance(as_of), "event_id": event_id, "tier_key": None,
                "history": [], "forecast": [], "recommendation": None,
                "unforecastable_reason": "no_snapshots"}

    history = con.execute(
        """
        SELECT as_of_date, days_until_event, get_in_price, median_price, listing_count
        FROM price_snapshots
        WHERE event_id = ? AND tier_key = ? AND NOT is_burn_in AND as_of_date <= ?
        ORDER BY as_of_date
        """,
        [event_id, tier_key, as_of],
    ).df()

    forecast = serve.forecast_curve(con, event_id, tier_key, as_of)
    recommendation = serve.recommend(con, event_id, tier_key, as_of)

    return {
        **_provenance(as_of),
        "event_id": event_id,
        "tier_key": tier_key,
        "history": [
            {
                "date": _iso(r["as_of_date"]),
                "days_until_event": int(r["days_until_event"]),
                "get_in_price": round(float(r["get_in_price"]), 2),
                "median_price": round(float(r["median_price"]), 2),
                "listing_count": int(r["listing_count"]),
            }
            for r in _records(history)
        ],
        "forecast": [
            {"date": p.as_of_date, "days_until_event": p.days_until_event,
             "horizon_days": p.horizon_days, "q10": p.q10, "q50": p.q50, "q90": p.q90}
            for p in forecast
        ],
        "recommendation": recommendation.__dict__,
    }


@app.get("/api/events/{event_id}/tiers")
def event_tiers(event_id: int, con=Depends(get_connection), as_of: date = Depends(resolve_as_of)):
    """Per-seat-tier recommendations, best expected saving first."""
    return {**_provenance(as_of), "event_id": event_id,
            "tiers": serve.recommend_all_tiers(con, event_id, as_of)}


# ---------------------------------------------------------------------------
# Venues, teams, accuracy
# ---------------------------------------------------------------------------


@app.get("/api/venues")
def venues(con=Depends(get_connection), as_of: date = Depends(resolve_as_of),
           q: str | None = None, limit: int = Query(200, le=500)):
    clause, params = "", [as_of]
    if q:
        clause = "AND (lower(v.venue_name) LIKE ? OR lower(v.city) LIKE ?)"
        params += [f"%{q.lower()}%"] * 2
    rows = con.execute(
        f"""
        SELECT v.venue_id, v.venue_name, v.city, v.region, v.archetype, v.capacity,
               count(e.event_id) FILTER (WHERE e.event_date > ?) AS upcoming_events,
               v.event_count AS total_events
        FROM venues v LEFT JOIN events e USING (venue_id)
        WHERE 1=1 {clause}
        GROUP BY 1,2,3,4,5,6,8 ORDER BY upcoming_events DESC, v.venue_name LIMIT {int(limit)}
        """,
        params,
    ).df()
    return {**_provenance(as_of), "venues": _records(rows)}


@app.get("/api/teams")
def teams(con=Depends(get_connection), as_of: date = Depends(resolve_as_of),
          q: str | None = None, limit: int = Query(200, le=500)):
    clause, params = "", [as_of]
    if q:
        clause = "AND lower(e.home_team) LIKE ?"
        params.append(f"%{q.lower()}%")
    rows = con.execute(
        f"""
        SELECT e.home_slug AS slug, e.home_team AS name, e.league,
               count(*) FILTER (WHERE e.event_date > ?) AS upcoming_events,
               min(v.venue_name) AS home_venue
        FROM events e JOIN venues v USING (venue_id)
        WHERE e.home_team IS NOT NULL {clause}
        GROUP BY 1,2,3 HAVING upcoming_events > 0
        ORDER BY upcoming_events DESC LIMIT {int(limit)}
        """,
        params,
    ).df()
    return {**_provenance(as_of), "teams": _records(rows)}


@app.get("/api/accuracy")
def accuracy(as_of: date = Depends(resolve_as_of)):
    """Backtest and training metrics, with the caveat attached to the numbers."""
    payload: dict[str, Any] = {**_provenance(as_of)}
    for name, filename in (("backtest", "backtest.json"), ("training", "training_metrics.json")):
        path = REPORT_DIR / filename
        payload[name] = json.loads(path.read_text()) if path.exists() else None
    payload["interpretation"] = (
        "These figures are measured on simulated prices. They demonstrate that the "
        "pipeline recovers timing structure it was not trained on -- the backtest scores "
        "events the model never saw -- but they are NOT evidence that the model would "
        "predict real ticket prices well. Connect a live price collector to measure that."
    )
    return payload


# ---------------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------------


class AlertRuleIn(BaseModel):
    event_id: int
    rule_type: str = Field(description="model_buy | target_price | drop_pct")
    tier_key: str | None = None
    threshold: float | None = None
    channel: str = "inapp"
    destination: str | None = None
    label: str | None = None


@app.post("/api/alerts/rules", status_code=201)
def create_alert_rule(payload: AlertRuleIn, con=Depends(get_connection)):
    try:
        rule_id = alerts.create_rule(
            con, payload.event_id, payload.rule_type, payload.tier_key,
            payload.threshold, payload.channel, payload.destination, payload.label,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    return {"rule_id": rule_id}


@app.get("/api/alerts/rules")
def list_alert_rules(con=Depends(get_connection)):
    rows = con.execute(
        """
        SELECT r.*, e.name AS event_name, e.event_date, e.url AS purchase_url
        FROM alert_rules r JOIN events e USING (event_id)
        ORDER BY r.created_at DESC
        """
    ).df()
    return {"rules": _records(rows)}


@app.delete("/api/alerts/rules/{rule_id}")
def delete_alert_rule(rule_id: str, con=Depends(get_connection)):
    con.execute("UPDATE alert_rules SET active = FALSE WHERE rule_id = ?", [rule_id])
    return {"rule_id": rule_id, "active": False}


@app.post("/api/alerts/evaluate")
def evaluate_alerts(con=Depends(get_connection), as_of: date = Depends(resolve_as_of)):
    return {**_provenance(as_of), "fired": alerts.evaluate(con, as_of)}


@app.get("/api/alerts")
def list_alerts(con=Depends(get_connection), limit: int = Query(100, le=500)):
    rows = con.execute(
        """
        SELECT a.*, e.name AS event_name, e.event_date, r.rule_type, r.channel
        FROM alert_events a
        JOIN events e USING (event_id)
        LEFT JOIN alert_rules r USING (rule_id)
        ORDER BY a.fired_at DESC LIMIT ?
        """,
        [limit],
    ).df()
    return {"alerts": _records(rows), "source": SYNTHETIC_SOURCE, "is_simulated": True}


@app.post("/api/alerts/{alert_id}/ack")
def acknowledge(alert_id: str, con=Depends(get_connection)):
    con.execute("UPDATE alert_events SET acknowledged = TRUE WHERE alert_id = ?", [alert_id])
    return {"alert_id": alert_id, "acknowledged": True}
