"""Central configuration for TixTime.

Everything that another module might want to tune lives here so the pipeline
stays reproducible: the same config plus the same source CSV always produces
the same warehouse, the same models and the same backtest numbers.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
ARTIFACT_DIR = DATA_DIR / "artifacts"
REPORT_DIR = DATA_DIR / "reports"

RAW_EVENTS_CSV = RAW_DIR / "seatgeek_events.csv"
WAREHOUSE = DATA_DIR / "tixtime.duckdb"

# ---------------------------------------------------------------------------
# The as-of clock
# ---------------------------------------------------------------------------
# The supplied SeatGeek export covers events from 2025-10-10 to 2026-07-24.
# Wall-clock "today" is past nearly all of them, which would leave a
# buy-timing product with nothing to recommend. So the whole system runs
# against an explicit as-of date: events before it are history (training and
# backtesting), events after it are the upcoming shows the site recommends on.
#
# This is not a hack to hide the data's age -- it is the same mechanism the
# backtester uses to replay any past date, and the UI displays it prominently.
DEFAULT_AS_OF = date(2025, 11, 1)


def as_of_date() -> date:
    """As-of date, overridable with TIXTIME_AS_OF=YYYY-MM-DD."""
    raw = os.environ.get("TIXTIME_AS_OF")
    if not raw:
        return DEFAULT_AS_OF
    return date.fromisoformat(raw.strip())


# ---------------------------------------------------------------------------
# Simulation / modelling windows
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SimulationConfig:
    """Bounds for the synthetic price-history generator."""

    # Snapshots start at the event's real announceDate but never earlier than
    # this many days before the event -- beyond it, resale listings are thin
    # enough that a modelled price is meaningless.
    max_lead_days: int = 240
    # Events with a shorter announce->event window than this are skipped for
    # modelling: too few observations to compute 30-day rolling features.
    min_lead_days: int = 45
    # Random seed. Combined with eventId this makes every event's price path
    # deterministic and reproducible across runs and machines.
    seed: int = 20260731

    def __post_init__(self) -> None:
        if self.min_lead_days >= self.max_lead_days:
            raise ValueError("min_lead_days must be < max_lead_days")


SIMULATION = SimulationConfig()

# Rolling feature windows (days). The longest one sets how much warm-up
# history every modelled row needs.
ROLLING_WINDOWS = (7, 14, 30)
WARMUP_DAYS = max(ROLLING_WINDOWS)

# A purchase counts as "good" if it lands within this multiple of the best
# price still available at the time of the decision.
NEAR_MIN_TOLERANCE = 1.03

# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------
# Every price row carries a source tag. Real collector output would be tagged
# with the provider name ("seatgeek", "ticketmaster"); anything generated by
# tixtime.pricing.simulator is tagged SYNTHETIC_SOURCE and the API and UI
# label it as such. Nothing in the codebase may present a synthetic row as an
# observed market price.
SYNTHETIC_SOURCE = "synthetic_v1"
REAL_SOURCES = ("seatgeek", "ticketmaster")


def is_synthetic(source: str) -> bool:
    return source not in REAL_SOURCES
