import { Action } from '../lib/api';

/**
 * The ONLY component allowed to render a currency figure.
 *
 * It refuses to render without a provenance token. A `source` column in the
 * database is invisible at the surface where harm happens and is dropped by
 * the first join or aggregation; requiring it here means a simulated dollar
 * amount cannot reach the screen unlabelled. Tooltips and screenshots travel;
 * a page-level banner does not travel with them.
 */
export function Price({
  value,
  source,
  size = 'md',
  tone,
}: {
  value: number | null | undefined;
  source: string | undefined;
  size?: 'sm' | 'md' | 'lg' | 'hero';
  tone?: 'good' | 'warn' | 'muted';
}) {
  if (value === null || value === undefined) return <span className="muted mono">—</span>;
  if (!source) {
    // Loud on purpose: a missing provenance token is a bug, not a fallback.
    return <span title="missing provenance" style={{ color: 'var(--status-critical)' }}>?</span>;
  }
  const fontSize = { sm: 12, md: 14, lg: 20, hero: 38 }[size];
  const weight = size === 'hero' || size === 'lg' ? 650 : 500;
  const color =
    tone === 'good' ? 'var(--status-good)'
    : tone === 'warn' ? 'var(--status-warn)'
    : tone === 'muted' ? 'var(--text-muted)'
    : undefined;
  return (
    <span
      className="mono"
      style={{ fontSize, fontWeight: weight, color, letterSpacing: '-0.02em' }}
      title={`${source === 'synthetic_v1' ? 'Simulated price' : source}: $${value.toFixed(2)}`}
    >
      ${value >= 1000 ? value.toLocaleString(undefined, { maximumFractionDigits: 0 })
        : value.toFixed(value < 100 ? 2 : 0)}
    </span>
  );
}

export function SyntheticRibbon({ disclaimer }: { disclaimer?: string }) {
  return (
    <div className="synthetic-ribbon">
      <span className="chip-synthetic">Simulated prices</span>
      <span>
        {disclaimer ??
          'Prices on this site are generated by TixTime’s market simulator. Event names, dates, venues and purchase links are real.'}
      </span>
    </div>
  );
}

export function ActionChip({ action, confidence }: { action: Action | null; confidence?: string | null }) {
  if (!action || action === 'NO_FORECAST') return <span className="chip chip-none">No forecast</span>;
  const isBuy = action === 'BUY_NOW';
  return (
    <span className={isBuy ? 'chip chip-buy' : 'chip chip-wait'}>
      {isBuy ? '● Buy now' : '◔ Wait'}
      {confidence ? <span style={{ opacity: 0.75, fontWeight: 500 }}>· {confidence}</span> : null}
    </span>
  );
}

export function Stat({
  label, value, note, tone,
}: { label: string; value: React.ReactNode; note?: string; tone?: 'good' | 'warn' }) {
  const color = tone === 'good' ? 'var(--status-good)' : tone === 'warn' ? 'var(--status-warn)' : undefined;
  return (
    <div className="stat">
      <div className="stat-label">{label}</div>
      <div className="stat-value" style={{ color }}>{value}</div>
      {note ? <div className="stat-note">{note}</div> : null}
    </div>
  );
}

/**
 * Sparkline for search cards. Deliberately axis-free and unlabelled: it shows
 * shape only, and every card that carries one also carries the actual price as
 * a <Price>, so the trace is never the sole source of a number.
 */
export function Sparkline({
  points, color = 'var(--series-1)', width = 108, height = 30,
}: { points: number[] | null; color?: string; width?: number; height?: number }) {
  if (!points || points.length < 2) return <div style={{ width, height }} />;
  const min = Math.min(...points);
  const max = Math.max(...points);
  const span = max - min || 1;
  const step = width / (points.length - 1);
  const path = points
    .map((p, i) => `${i === 0 ? 'M' : 'L'}${(i * step).toFixed(1)},${(height - ((p - min) / span) * height).toFixed(1)}`)
    .join(' ');
  const last = points[points.length - 1];
  const lastY = height - ((last - min) / span) * height;
  return (
    <svg width={width} height={height} style={{ display: 'block', overflow: 'visible' }} aria-hidden="true">
      <path d={path} fill="none" stroke={color} strokeWidth={1.75} strokeLinejoin="round" strokeLinecap="round" />
      <circle cx={width} cy={lastY} r={2.75} fill={color} stroke="var(--surface-raised)" strokeWidth={1.5} />
    </svg>
  );
}

export function Loading({ rows = 6, height = 74 }: { rows?: number; height?: number }) {
  return (
    <div className="col">
      {Array.from({ length: rows }, (_, i) => (
        <div key={i} className="skeleton" style={{ height }} />
      ))}
    </div>
  );
}

export function Empty({ title, detail }: { title: string; detail?: string }) {
  return (
    <div className="empty">
      <div style={{ fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>{title}</div>
      {detail ? <div className="small">{detail}</div> : null}
    </div>
  );
}

const REASON_COPY: Record<string, { title: string; detail: string }> = {
  date_tbd: {
    title: 'Date to be confirmed',
    detail:
      'This is a playoff placeholder — the opponent and date are not set, so there is no price path to forecast. Watch the matchup and it will start forecasting once the date is fixed.',
  },
  past_event: {
    title: 'This event has already happened',
    detail:
      'Relative to the simulated clock this date is in the past. Its realised price history is shown below, with no forecast.',
  },
  no_snapshots: {
    title: 'No price history',
    detail: 'No listing observations exist for this event, so nothing can be forecast from it.',
  },
  non_game_inventory: {
    title: 'Not a ticketed seat',
    detail:
      'This is a tour, tailgate, suite or party listing rather than a seated game, so seat-tier timing does not apply.',
  },
  tbd_placeholder: {
    title: 'Placeholder event',
    detail: 'A provisional postseason slot with no confirmed date or opponent.',
  },
  board_not_built: {
    title: 'Rankings not built for this clock date',
    detail:
      'The ranked deal board is precomputed for one date at a time, and the clock is currently set to a different one. The price history and forecast below are still computed live and are correct; only the cross-event ranking and the buy signal are unavailable. Rebuild the board for this date, or move the clock back to the board’s date.',
  },
  insufficient_lead_time: {
    title: 'Announced too close to the event',
    detail:
      'Fewer than 45 days between announcement and event — too little history to compute the rolling features the model needs.',
  },
};

/** Named states for the known-bad slices, rather than an empty chart. */
export function UnforecastableNotice({ reason }: { reason: string | null }) {
  const copy = REASON_COPY[reason ?? ''] ?? {
    title: 'No forecast available',
    detail: 'This event is outside the modelled set.',
  };
  return (
    <div className="empty" style={{ textAlign: 'left', padding: '28px 24px' }}>
      <div style={{ fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6 }}>{copy.title}</div>
      <div className="small" style={{ maxWidth: '62ch' }}>{copy.detail}</div>
    </div>
  );
}

/** Shown whenever the clock sits off the precomputed board's date. Being
 * explicit here is the point: the alternative is silently serving rankings
 * derived from prices dated after the date the page claims. */
export function BoardStaleNotice({ note }: { note?: string }) {
  if (!note) return null;
  return (
    <div
      className="card card-pad small"
      style={{
        marginBottom: 14,
        borderColor: 'rgba(201,133,0,.45)',
        background: 'var(--status-warn-dim)',
        color: '#f0d9a8',
      }}
    >
      <strong style={{ color: '#fff' }}>Rankings unavailable at this clock date. </strong>
      {note}
    </div>
  );
}

export function formatDate(value: string | null | undefined, opts?: Intl.DateTimeFormatOptions) {
  if (!value) return '—';
  const date = new Date(value.length <= 10 ? `${value}T00:00:00` : value);
  return date.toLocaleDateString(undefined, opts ?? { month: 'short', day: 'numeric', year: 'numeric' });
}

export function formatPct(value: number | null | undefined, digits = 0) {
  if (value === null || value === undefined) return '—';
  return `${(value * 100).toFixed(digits)}%`;
}
